- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties?
  value:
    cloud-provider:
      type: vsphere
      vsphere:
        user: ((vcenter_user))
        password: ((vcenter_password))
        server: ((vcenter_ip))
        insecure-flag: 1
        datacenter: ((vcenter_dc))
        datastore: ((vcenter_ds))
        working-dir: /((vcenter_dc))/vm/((vcenter_vms))/((director_uuid))

- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/provides?
  value:
    cloud-provider: {as: master}

- type: replace
  path: /instance_groups/name=master/jobs/name=kubernetes-system-specs/consumes?
  value:
    cloud-provider: {from: master}
