azs:
- name: z1
  cloud_properties:
    availability_zone: ((az))
- name: z2
  cloud_properties:
    availability_zone: ((az))
- name: z3
  cloud_properties:
    availability_zone: ((az))

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

networks:
- name: ((deployments_network))
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [((dns_recursor_ip))]
    reserved: [((internal_gw))/30]
    cloud_properties:
      subnet: ((subnet_id))

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: worker
  network: ((deployments_network))
