platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-deployment/ci/scripts/upload-kubo-release.sh

inputs:
  - name: git-kubo-deployment
  - name: git-kubo-release
  - name: s3-bosh-creds
outputs:
  - name: s3-kubo-release-tarball
