name: cfcr

releases:
- name: kubo
  version: 0.9.0
  url: https://github.com/cloudfoundry-incubator/kubo-release/releases/download/v0.9.0/kubo-release-0.9.0.tgz
  sha1: e88722e12cce75b7db688da42564fc3f61715dbf
- name: kubo-etcd
  version: 5
  url: https://github.com/pivotal-cf-experimental/kubo-etcd/releases/download/v5/kubo-etcd.5.tgz
  sha1: 23ed1754048ff758ed8fdf75ee1369ca59435181
- name: docker
  version: 30.1.4
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.1.4/docker-30.1.4.tgz
  sha1: f79a70452b3ddae52f5ac78dd37ff8d9e6ec19e2
- name: bosh-dns
  sha1: e38d3e5edd16ce2dca778440b636ab1ea61f892f
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.0.11
  version: 0.0.11

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3468.latest

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
- name: kubo-dns-aliases
  release: kubo

instance_groups:
- name: master
  instances: 1
  networks:
  - name: default
  azs: [z1,z2,z3]
  jobs:
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      backend_port: 8443 # Bosh links hack
      port: 8443
      authorization-mode: rbac
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      authorization-mode: rbac
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
        delete_data_dir_on_stop: false
  stemcell: trusty
  vm_type: small
  persistent_disk: 5120

- name: worker
  instances: ((worker_count))
  networks:
  - name: default
  azs: [z1,z2,z3]
  jobs:
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      bip: 172.17.0.1/24
      flannel: true
      iptables: false
      ip_masq: false
      log_level: error
      store_dir: /var/vcap/data
      storage_driver: overlay
      default_ulimits: [ "nofile=65536" ]
      tls_cacert: ((tls-docker.ca))
      tls_cert:  ((tls-docker.certificate))
      tls_key: ((tls-docker.private_key))
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: "https://master.kubo:8443"
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubelet
    release: kubo
    properties:
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
  stemcell: trusty
  vm_type: small-highmem
  persistent_disk: 10240

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kube-proxy-password
  type: password
- name: kube-scheduler-password
  type: password
- name: route-sync-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    organization: "system:nodes"
    common_name: kubelet.kubo.internal
    alternative_names: []
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    organization: "system:masters"
    common_name: master.kubo
    alternative_names:
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - master.kubo
- name: tls-docker
  type: certificate
  options:
    ca: kubo_ca
    common_name: docker.kubo.internal

- name: /dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca
- name: /dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth
- name: /dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

features:
  use_dns_addresses: true
