---
azs:
- name: z1
  cloud_properties:
    zone: ((zone))

networks:
- name: &network_name ((deployments_network))
  type: dynamic
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    dns:
    - ((dns_recursor_ip))
    az: z1
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: false

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 4
  network: *network_name
  az: z1
  reuse_compilation_vms: true
  vm_type: worker
