internal_ip: # Internal ip address of the BOSH director. Please select an available ip address in the network you wish to deploy into. 

deployments_network: # Network name to deploy service in your cloud config

cf-tcp-router-name: # URL to TCP router. In PCF: tcp.<domain>
routing-cf-api-url: # TCP routing API URL. In PCF: https://api.<system domain>
routing-cf-client-id: # Routing UAA client name that will be used to register tcp routes
routing-cf-uaa-url: # Routing UAA URL In PCF: https://uaa.<system domain>

# we use BOSH 261 since CredHub 0.4 supports only it
# CredHub 0.4 fixes important bug that breaks deployment
bosh_release_url: http://bosh.io/d/github.com/cloudfoundry/bosh?v=261.2 # URL to  261 bosh-director release https://s3.amazonaws.com/kubo-public/bosh-dev-release.tgz, or link to a local file
bosh_release_sha1: d4635b4b82b0dc5fd083b83eb7e7405832f6654b # SHA1 of latest stable 261 bosh-director release

credhub_encryption_key: # 16 byte number in HEX format: i.e. ABCDEF0123456789ABCDEF0123456789

director_name: # user friendly Director name
dns_recursor_ip: # DNS IP address. Usually the same as gateway, see below
internal_cidr: # CIDR range that BOSH will deploy to
internal_gw: # internal gateway

stemcell_version: # version of the stemcell used in all Kubo deployments
stemcell_url: # path to a stemcell used in all Kubo deployments
syslog-endpoint: ""

credhub_release_url: https://s3.amazonaws.com/kubo-public/credhub-0.4.0.tgz
kubo_release_url: https://s3.amazonaws.com/kubo-public/kubo-release.tgz

