azs:
- name: z1
  cloud_properties:
    availability_zone: ((az))

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

networks:
- name: ((deployments_network))
  type: dynamic
  subnets:
  - azs: [z1]
    dns: [((dns_recursor_ip))]
    cloud_properties:
      net_id: ((net_id))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: worker
  network: ((deployments_network))
