---
resources:
- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-deployment
    branch: master
    private_key: {{git-ssh-key}}

- name: kubo-lock
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: {{git-ssh-key}}
    pool: kubo-deployment

- name: s3-bosh-state
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    versioned_file: bosh/state.json

- name: s3-bosh-creds
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: kubo-pipeline
    endpoint: s3-eu-west-1.amazonaws.com
    region_name: eu-west-1
    versioned_file: bosh/creds.yml

jobs:
- name: claim-lock
  plan:
  - get: git-kubo-deployment
    trigger: true
  - put: kubo-lock
    params: { acquire: true }

- name: install-bosh
  plan:
  - get: git-kubo-deployment
    trigger: true
    passed: [ 'claim-lock' ]
  - get: kubo-lock
    passed: [ 'claim-lock' ]
  - task: install
    file: git-kubo-deployment/ci/tasks/install-bosh.yml
    params:
      GCP_SERVICE_ACCOUNT: {{gcp-service-account}}
  - aggregate:
    - put: s3-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: s3-bosh-state
      params:
        file: bosh-state/state.json

- name: run-k8s-tests
  plan:
  - aggregate:
    - get: git-kubo-deployment
      trigger: true
      passed: [ 'install-bosh' ]
      trigger: true
    - get: kubo-lock
      passed: [ 'install-bosh' ]
    - get: s3-bosh-creds
      passed: [ 'install-bosh' ]
    - get: s3-bosh-state
      passed: [ 'install-bosh' ]
  - task: install
    file: git-kubo-deployment/ci/tasks/deploy-k8s-instance.yml

- name: destroy-bosh
  plan:
  - aggregate:
    - get: git-kubo-deployment
      passed: [ 'run-k8s-tests' ]
      trigger: true
    - get: kubo-lock
      passed: [ 'run-k8s-tests' ]
    - get: s3-bosh-creds
      passed: [ 'run-k8s-tests' ]
    - get: s3-bosh-state
      passed: [ 'run-k8s-tests' ]
  - task: destroy
    file: git-kubo-deployment/ci/tasks/destroy-bosh.yml
    params:
      GCP_SERVICE_ACCOUNT: {{gcp-service-account}}
  - put: kubo-lock
    params: { release: kubo-lock }
