---
resources:
- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-deployment
    branch: pr-e2e-ci
    private_key: {{git-ssh-key}}

jobs:
- name: install-bosh
  plan:
  - get: git-kubo-deployment
  - task: gcp
    file: git-kubo-deployment/ci/tasks/install-bosh.yml
