- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-provider/gce/service_key?
  value: ((service_key_worker))
- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-provider/gce/service_key?
  value: ((service_key_master))
